# Generated by Django 5.2.6 on 2026-08-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_post_remove_blogarticle_tags_delete_chatlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
