# Generated by Django 5.2.6 on 2026-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_user_avatar_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
