# Generated by Django 5.2.6 on 2026-08-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_user_avatar_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image_key",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
