# Generated by Django 5.2.6 on 2026-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_chatlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogarticle",
            name="content_type",
            field=models.CharField(
                choices=[("blog", "ブログ記事"), ("qa", "Q&A")],
                default="blog",
                max_length=10,
            ),
        ),
    ]
