# Generated by Django 5.2.6 on 2026-09-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_post_image_content_type_post_image_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
