# Generated by Django 5.2.6 on 2026-09-13 07:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_accountapplicationverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
