# Generated by Django 5.2.6 on 2026-09-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_post_liked_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
