# Generated by Django 5.2.6 on 2026-09-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_user_profile_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_status",
            field=models.CharField(
                choices=[
                    ("active", "利用中"),
                    ("suspended", "凍結中"),
                    ("banned", "永久停止"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
